# Generated by Django 5.1.4 on 2026-09-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default='POST', editable='False', primary_key=True, serialize=False)),
                ('callback_url', models.URLField()),
                ('method', models.CharField(default='POST', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
