# Generated by Django 5.1.4 on 2026-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DEAD', 'Dead')], default='CREATED', max_length=20),
        ),
    ]
