# Generated by Django 5.1.4 on 2026-09-27 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_task_attempts_task_max_retries_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('response_status', models.IntegerField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('error', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executor.task')),
            ],
        ),
    ]
