# Generated by Django 5.1.4 on 2026-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_taskattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DEAD', 'Dead'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
