# Generated by Django 5.1.4 on 2026-10-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeout',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='response_body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
