from django.db import models
import uuid
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):

    #nested class to specify the status choices
    class Status(models.TextChoices):
        CREATED = "CREATED"
        QUEUED = "QUEUED"
        RUNNING = "RUNNING"
        SUCCESS = "SUCCESS"
        FAILED = "FAILED"
        DEAD = "DEAD"
        CANCELLED = "CANCELLED"

    #primary key and unique identifier generated by the uuid4 function
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);

    #url sent by user fot the worker to call
    callback_url=models.URLField()

    #method used while calling the url
    method=models.CharField(max_length=10,default="POST")

    ##JSON data sent along with the call
    payload=models.JSONField(default=dict)

    #current status of the task
    status=models.CharField(max_length=20,choices=Status.choices,default=Status.CREATED)

    created_at=models.DateTimeField(auto_now_add=True)

    updated_at=models.DateTimeField(auto_now=True)

    attempts = models.IntegerField(default=0)

    max_retries = models.IntegerField(default=3)

    #Max time of wait for the response from the callback url to prevent indefinite waiting time.
    timeout = models.IntegerField(default=10)

#info about each attempt of the task
class TaskAttempt(models.Model):
    #foregin key is the instance of Task model
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    attempt_number = models.IntegerField()

    status = models.CharField(max_length=20)

    response_status = models.IntegerField(null=True)

    duration = models.FloatField(null=True)

    error = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    #response from the callback url
    response_body = models.JSONField(null=True, blank=True)


# class APIKey(models.Model):

#     key=models.CharField(max_length=64, unique=True)

#     user=models.ForeignKey(User,on_delete=models.CASCADE)

#     created_at=models.DateTimeField(auto_now_add=True)

#     is_active=models.BooleanField(defult=True)
