from django.db import models
import uuid

# Create your models here.
class Task(models.Model):

    #nested class to specify the status choices
    class Status(models.TextChoices):
        CREATED = "CREATED"
        QUEUED = "QUEUED"
        RUNNING = "RUNNING"
        SUCCESS = "SUCCESS"
        FAILED = "FAILED"
        DEAD = "DEAD"

    #primary key and unique identifier generated by the uuid4 function
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False);

    #url sent by user fot the worker to call
    callback_url=models.URLField()

    #method used while calling the url
    method=models.CharField(max_length=10,default="POST")

    ##JSON data sent along with the call
    payload=models.JSONField(default=dict)

    #current status of the task
    status=models.CharField(max_length=20,choices=Status.choices,default=Status.CREATED)

    created_at=models.DateTimeField(auto_now_add=True)

    updated_at=models.DateTimeField(auto_now=True)

    attempts = models.IntegerField(default=0)

    max_retries = models.IntegerField(default=3)